### ISSUE TITLE
怎么把输入框置空

### ISSUE THREAD

**Issue by janepanye** [xjh093/JHVerificationCodeView#1]

**Comment by xjh093** [comment]
有这个需求？要一键清空？

**Comment by janepanye** [comment]
好了。我便利了子控件。




| |
潘晔
邮箱：panye26080@163.com
|

签名由 网易邮箱大师 定制

在2019年07月19日 18:17，HaoCold 写道：

有这个需求？要一键清空？

**Comment by xjh093** [comment]
我添加了一个方法，一键清空所有输入内容。

**Comment by xjh093** [comment]
就不用再遍历子控件了。

**Comment by janepanye** [comment]
👌




| |
潘晔
邮箱：panye26080@163.com
|

签名由 网易邮箱大师 定制

在2019年07月19日 18:45，HaoCold 写道：

就不用再遍历子控件了。
