### ISSUE TITLE
Xib support?

### ISSUE THREAD

**Issue by likeSo** [xjh093/JHVerificationCodeView#3]
参数必须初始化的时候传入？如果我是使用XIB初始化的呢？

**Comment by likeSo** [comment]
另外，有一个较为常见的需求是验证码输入错误，能否加入一个动态修改下划线颜色的需求？验证码输入错误了，把下划线全都改为红色？😅

**Comment by xjh093** [comment]
Xib支持，有空看看是否可行。

**Comment by xjh093** [comment]
输入错误的情况，是在验证码全部输入完成的时候吧。
这个时候调用方法，把颜色全部修改。
如果回删字符的时候，应该就不显示错误颜色了吧？

**Comment by xjh093** [comment]
@likeSo 
由于 IBInspectable 属性支持修饰的属性类型是：
BOOL、NSNumber、CGPoint、CGSize、CGRect、UIColor、NSString、NSLocalizedString、NSRange、UIImage、NSNull
所以自定义的对象就没办法了

**Comment by likeSo** [comment]
你上面说的是对的，就是错误的时候显示红字，重新输入了改回默认颜色。其实我们的需求更变态，输入了变颜色，没输入显示灰色，我现在自己写好了🤣

**Comment by xjh093** [comment]
@likeSo 添加了输入完成状态属性，可以调用方法设置最终状态。

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  JHVerificationCodeView (1.3.6) successfully published
 📅  December 23rd, 20:48
 🌎  https://cocoapods.org/pods/JHVerificationCodeView
 👍  Tell your friends!
--------------------------------------------------------------------------------
