### ISSUE TITLE
哥们，我autoShowKeyboard = YES 的时候，进入页面键盘会闪几下，不知道是为什么

### ISSUE THREAD

**Issue by TianYou899** [xjh093/JHVerificationCodeView#7]
如标题

**Comment by TianYou899** [comment]
我把push 动画关闭的时候键盘就不会闪了，可能自动弹起键盘的操作坐下延迟会更好点。

**Comment by xjh093** [comment]
要不加个延迟属性吧

**Comment by xjh093** [comment]
加了个延迟属性：`autoShowKeyboardDelay`
enjoy yourself~

**Comment by TianYou899** [comment]
哥们，我用cocoaPods 拉下来最新的1.3.6没有这个属性，是不是需要升级版本？

**Comment by xjh093** [comment]
我还没发到 cocoaPods，我是打算先让你测一下，没问题就发 :)

**Comment by xjh093** [comment]
🎉  Congrats

 🚀  JHVerificationCodeView (1.3.7) successfully published
 📅  September 9th, 03:48
 🌎  https://cocoapods.org/pods/JHVerificationCodeView
 👍  Tell your friends!

**Comment by TianYou899** [comment]
手下我的膝盖，大佬666

**Comment by xjh093** [comment]
😂😂😂

**Comment by TianYou899** [comment]
感谢！！！
